module Crig
  {% begin %}
    {% version_line = read_file("#{__DIR__}/../shard.yml").lines.select(&.starts_with?("version:")).first %}
    VERSION = {{ version_line.split(":").last.strip }}
  {% end %}
  UPSTREAM_URL         = "https://github.com/0xPlaygrounds/rig.git"
  UPSTREAM_COMMIT      = "9fc7dc3d6e9b26b0c9f81f443067b995a51fad75"
  UPSTREAM_SOURCE_PATH = "vendor/rig/crates/rig-core"
end

require "./crig/completion"
require "./crig/markers"
require "./crig/concurrency"
require "./crig/embeddings"
require "./crig/memory"
require "./crig/memory/policies"
require "./crig/tool"
require "./crig/tool/extensions"
require "./crig/tool/result"
require "./crig/tool/rmcp"
require "./crig/tool/server"
require "./crig/tools/think"
require "./crig/evals"
require "./crig/extractor"
require "./crig/streaming_traits"
require "./crig/streaming"
require "./crig/agent"
require "./crig/agent/prompt_request"
require "./crig/agent/prompt_request/streaming"
require "./crig/image_generation"
require "./crig/http_client"
require "./crig/json_utils"
require "./crig/id"
require "./crig/provider_response"
require "./crig/rerank"
require "./crig/loaders"
require "./crig/model"
require "./crig/one_or_many"
require "./crig/telemetry"
require "./crig/wasm_compat"
require "./crig/audio_generation"
require "./crig/transcription"
require "./crig/vector_store"
require "./crig/integrations"
require "./crig/client"
require "./crig/providers"
