module Crig
  VERSION              = "0.1.0"
  UPSTREAM_URL         = "https://github.com/0xPlaygrounds/rig.git"
  UPSTREAM_COMMIT      = "f5c4812de02e776d9a68b481a8cf71ed6b572a2d"
  UPSTREAM_SOURCE_PATH = "vendor/rig/rig/rig-core"
end

require "./crig/completion"
require "./crig/concurrency"
require "./crig/embeddings"
require "./crig/tool"
require "./crig/tool/rmcp"
require "./crig/tool/server"
require "./crig/tools/think"
require "./crig/evals"
require "./crig/extractor"
require "./crig/streaming_traits"
require "./crig/streaming"
require "./crig/agent"
require "./crig/agent/prompt_request"
require "./crig/agent/prompt_request/streaming"
require "./crig/image_generation"
require "./crig/http_client"
require "./crig/json_utils"
require "./crig/loaders"
require "./crig/model"
require "./crig/one_or_many"
require "./crig/telemetry"
require "./crig/wasm_compat"
require "./crig/audio_generation"
require "./crig/transcription"
require "./crig/vector_store"
require "./crig/pipeline"
require "./crig/integrations"
require "./crig/client"
require "./crig/providers"
