module Crig
  {% begin %}
    {% version_line = read_file("#{__DIR__}/../shard.yml").lines.select(&.starts_with?("version:")).first %}
    VERSION = {{ version_line.split(":").last.strip }}
  {% end %}
  UPSTREAM_URL               = "https://github.com/0xPlaygrounds/rig.git"
  UPSTREAM_COMMIT            = "68b4eabb8c9cf749ca73c917b9306e97fb0eda24"
  UPSTREAM_SOURCE_PATH       = "vendor/rig/crates/rig-core"
  UPSTREAM_SOURCE_PATH_AGENT = "vendor/rig/crates/rig-agent"
end

require "./crig/provider_response"
require "./crig/completion"
require "./crig/markers"
require "./crig/concurrency"
require "./crig/embeddings"
require "./crig/memory"
require "./crig/memory/policies"
require "./crig/tool"
require "./crig/tool/extensions"
require "./crig/tool/result"
require "./crig/tool/output"
require "./crig/tool/portable"
require "./crig/tool/rmcp"
require "./crig/tool/server"
require "./crig/tool/builtin/think"
require "./crig/evals"
require "./crig/extractor"
require "./crig/streaming_traits"
require "./crig/streaming"
require "./crig/agent"
require "./crig/agent/hook"
require "./crig/agent/run"
require "./crig/agent/run/streamed"
require "./crig/agent/streaming"
require "./crig/agent/runner"
require "./crig/agent/completion"
require "./crig/agent/prompt_request"
require "./crig/agent/prompt_request/streaming"
require "./crig/image_generation"
require "./crig/http_client"
require "./crig/json_utils"
require "./crig/id"
require "./crig/rerank"
require "./crig/loaders"
require "./crig/model"
require "./crig/one_or_many"
require "./crig/telemetry"
require "./crig/wasm_compat"
require "./crig/audio_generation"
require "./crig/transcription"
require "./crig/vector_store"
require "./crig/integrations"
require "./crig/client"
require "./crig/providers"
require "./crig/providers/internal/embedding_compatible"
require "./crig/prelude"
